behaviors:
  PostureTest:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 10000
      learning_rate: 3.0e-2
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 4
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 1000000
    time_horizon: 512
    summary_freq: 12000